- lib/hooks/useInterval.js
- lib/index.d.ts
Added `useInterval` hook
- Takes in a callback function as first argument, which runs after a certain delay
- Initial delay as second argument
- Returns two functions, `start` and `stop` for pausing and restarting the timer.
> added useInterval Hook

- lib/hooks/useSize.js
- lib/index.d.ts
- lib/index.js
- declared initial piece of state with `{width : 0, height : 0}`
- updates the height and width using [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) inside `useEffect`
> useSize hook added

- lib/hooks/useDeviceOS.js
- lib/index.d.ts
- lib/index.js
This pr adds useDeviceOS hook. 
1. It uses the browser navigator.userAgentData to find the user os.
2. If also detects the OS of the mobile emulators used in the browsers.
> In the case of a very special/new OS, it uses string manipulation to get OS out of userAgent
> feat/19 -Adds useDeviceOSHook

- lib/hooks/useConfirmExit.ts
- lib/hooks/useHold.ts
Hey @DavidHDev love this project, it's been my go-to for everything related to React Hooks for years now. 
I typically like working with source code over npm where I can, in grabbing the latest from `main` I ran into some relative pathing errors in the browser. Based on the conventions you've established, I believe it to be a legit bug.
I didn't see ticket for it and given I already had to resolve it on my end, I figured I'd kindly submit a fix. 🙂 
Feel free to decline, LMK if you have any questions and mostly thank you for making hooks sensible to me
> fix relative paths

- docs/demo/UseWindowSizeDemo.jsx
- docs/docs/hooks/useWindowSize.mdx
**Description**
Added ```UseWindowSizeDemo.jsx``` and ```useWindowSize.mdx``` files for documentation details.
Acceptance Criteria
**Note**
```useWindowSize``` is referenced in docs/readme but not in root/readme. 
**Demo:**
> Update: Adding missing documentation features for useWindowSize hook

- docs/README.md
- docs/demo/UseFullscreenDemo.jsx
- docs/docs/hooks/useFullscreen.mdx
**Description**
Added ```UseFullscreenDemo.jsx``` and ```useFullscreen.mdx``` files for documentation details. Also, added `useFullscreen` to `docs/README.md`.
Acceptance Criteria
**Note**
I added two examples to the `useFullscreen.mdx` file because I wasn't sure if this hook was _only_ supposed to be used for making a window fullscreen. The first example shows with the document.documentElement being used; however, if this was the intended purpose, couldn't it just be done in the hook itself?
It will also work with an element, but then _only_ that element is enlarged to fullscreen, not the entire document. I looked through previous pull requests but the one I saw mentioning it didn't explicitly define which purpose was intended, unless I overlooked it. If the option is intentional, I …
> Feature: added documentation and demo for useFullscreen hook

- lib/hooks/usePreventBodyScroll.ts
- lib/index.ts
**Description**
A hook that prevents body scrolling, is useful for modals or overlays.
**Acceptance Criteria**
**Details**
- The `usePreventBodyScroll` hook disables the scroll when active and enables when not active.
- The hook prevents body scrolling by setting `document.body.style.overflow` to `hidden` when active, ensuring the background remains static, which is particularly useful for modals or overlays.
- When the hook is deactivated or the component is unmounted, scrolling is automatically restored by resetting the empty style to an empty state.
- The hook provides a `toggleScrollLock` function that allows dynamic control of the scroll lock, enabling easy switching between locked and unlocked states.
- It returns a `boolean` state `isScrollLocked` that indicates whether scrolling …
> 59: [FEAT] Create Hook - usePreventBodyScroll()

- lib/hooks/useKeyPress.ts
- lib/index.ts
**Description**
A hook that detects when a specific key or combination of keys is pressed.
**Acceptance Criteria**
**Details:**
- **Single and Combination Key Detection**: The hook allows detection of individual key presses or key combinations (e.g., `['Control', 'Shift', 'X']` for `Ctrl + Shift + X`.
- **Key Management**: The hook uses a `Set` to track keys currently pressed. It compares this set with the target key set to determine if all required keys are pressed.
- **Event Handling**:
- The `keydown` event adds the pressed key to the set and checks if the required keys are pressed. If all keys are pressed, the callback is triggered.
- The `keyup` event removes the key from the set once it is released.
- The `blur` event clears the set to avoid lingering key states when the window …
> 62: [FEAT] Create Hook - useKeyPress()

- docs/demo/SwitchDemo.tsx
- docs/demo/demo.css
- docs/docs/utilities/switch.mdx
- lib/index.ts
- lib/old_index.d.ts
- lib/utils/Switch.test.tsx
- lib/utils/Switch.test.tsx.snap
- lib/utils/Switch.tsx
The `Switch` component can be used for complex conditional rendering. The component can be switch by multiple `"cases"` of components and an `"default"` component to render in case the given dynamic value does not match any case.
Render dynamic components cleanly using this component.
The `Switch` component accepts the following props:
- `value`            - the value to check with the cases to render the corresponding component.
- `components`       - the list of case components to be rendered when case matches.
- `defaultComponent` - the "default" component to be rendered if the value does not match any of the given cases.
**This component is useful for rendering a specific component as a dynamic value and can be written cleanly and explicitly**
✅ Added Switch component
✅ Added Switch …
> Added Switch component to utils

- lib/hooks/useInputValue.ts
- package-lock.json
This pull request fixes the return type in the `useInputValue()` hook, as mentioned in #106
Add the assertion `as const` to the return type of the hook.
> fix(hook): add `as const` assertion in `useInputValue` return type

- lib/tests/hooks/useEventListener.test.tsx
This PR adds a test to cover the behavior of the `useEventListener` hook. The test verifies that the hook correctly adds a listener for the click event and that the `handler` function is called when the event is triggered. Additionally, after unmounting the hook, a new click event is dispatched to ensure that the `handler` is not called again, validating the removal of the event listener.
> test(useEventListener): add test to verify event listener behavior

- lib/tests/hooks/useClipboard.test.tsx
This PR improves the reliability of`useClipboard()` hook test cases by properly handling state updates, async behavior, and error scenarios. 🚀
> Test/109: useClipboard() hook

- docs/demo/UsePreviousDemo.tsx
- docs/docs/hooks/usePrevious.mdx
- lib/hooks/usePrevious.ts
- lib/index.ts
- lib/tests/hooks/usePrevious.test.tsx
- package-lock.json
This pull request introduces a new `usePrevious()` hook to React Haiku, enabling easy track the previous value of some input in React applications.
```ts
import { usePrevious } from 'react-haiku';
export const UsePreviousComponent = () => {
const [count, setCount] = useState(0);
const prevCount = usePrevious(count);
function handleIncrement() {
setCount(prev => prev + 1)
}
function handleDecrement() {
setCount(prev => prev - 1)
}
return (
<div>
<h3>Current Value: {count}</h3>
<h3>Previous Value: {prevCount}</h3>
<div>
<button onClick={handleIncrement}>
Increment
</button>
<button onClick={handleDecrement}>
Decrement
</button>
</div>
</div>
);
}
```
> [READY] feat(hook): add `usePrevious` hook

- lib/hooks/useLeaveDetection.ts
- lib/tests/hooks/useLeaveDetection.test.tsx
The `useLeaveDetection` hook currently sets up the `mouseleave` event listener only once (due to the empty `useEffect` dependency). This means the hook always invokes the very first `onLeave` callback passed to it, rather than the latest one.
https://github.com/DavidHDev/haiku/blob/259ab50a9bc5b48de9141c1ae1d492c972e00705/lib/hooks/useLeaveDetection.ts#L3-L12
<br>
Now, this works in the documentation example because it uses the callback approach to update the state.
https://github.com/DavidHDev/haiku/blob/259ab50a9bc5b48de9141c1ae1d492c972e00705/docs/src/components/Demo/LeaveDetection.js#L5-L6
However, if the state is updated directly by passing a value, then the hook breaks, because it fails to invoke the latest callback everytime the `mouseleave` event occurs, instead it keeps calling …
> Fix `useLeaveDetection` to always invoke latest callback

- docs/demo/UseTimerDemo.jsx
- docs/docs/hooks/useTImer.mdx
- lib/hooks/useTimer.ts
- lib/index.ts
- lib/tests/hooks/useTImer.test.tsx
This PR introduces a custom`useTimer()` hook to manage timers with start, pause, and reset functionalities, supporting both counting up and down with customizable intervals.
- Implemented a new useTimer hook for managing timers with customizable start, pause, and reset features.
- Supports both counting up and down with configurable intervals.
- Added documentation for usage, API details, and example implementation.
```jsx
import { useTimer } from 'react-haiku';
export const TimerComponent = () => {
const { time, isRunning, start, pause, reset } = useTimer({
startTime: 0,
endTime: 10,
interval: 1000,
});
return (
<div>
<p>Time: {time}</p>
<button onClick={start} disabled={isRunning}>
Start
</button>
<button onClick={pause} disabled={!isRunning}>
Pause
</button>
<button …
```
> Feat/94: add `useTimer()` hook

- docs/demo/UsePermissionDemo.tsx
- docs/docs/hooks/usePermission.mdx
- lib/hooks/usePermission.ts
- lib/index.ts
- lib/tests/hooks/usePermission.test.tsx
This pull request introduces a new `usePermission()` hook mentioned in #95, enabling easy check browser permissions for querying status for various browser APIs in React applications.
```tsx
import { usePermission } from 'react-haiku';
export const Component = () => {
const state = usePermission("geolocation")
return (
<div>
<h3>Permission state: {state}</h3>
</div>
);
}
```
> feat(hook): add `usePermission` hook

- lib/helpers/event.ts
Fixed the off function to check for `removeEventListener` instead of `addEventListener`
> fix(event helpers): check for removeEventListener in off() instead of addEventListener

- lib/helpers/cookie.ts
- lib/hooks/useCookie.ts
- lib/hooks/useCookieListener.ts
- lib/hooks/useSingleEffect.ts
You've improved type safety in the `useCookieListener` hook in several key ways:
1. Added a generic type parameter `<T>` to the hook function signature, ensuring that the effect callback receives properly typed data
2. Made the effect callback parameters properly typed: `effect: (a: T, b: string) => void`
3. Used the generic type in `parseToDataType<T>()` to ensure the parsed cookie value matches the expected type
4. Added a check `if (parsedValue !== undefined)` to only call the effect when a valid value exists
5. Used a properly typed `Record<string, unknown>` for storing cookie values
These changes ensure type consistency throughout the cookie listening process and prevent potential runtime errors from mismatched types.
> refactor: enhance cookie hooks with type safety and parsing improvements

- docs/README.md
- docs/demo/UseGeolocationDemo.jsx
- docs/docs/hooks/useGeolocation.mdx
- lib/hooks/useGeolocation.ts
- lib/index.ts
- lib/tests/hooks/useGeolocation.test.tsx
Introduces a hook to access user geolocation using the browser's Geolocation API. Includes comprehensive error handling for permission requests and browser support.
- Provides usage documentation and examples
- Adds a demonstration component for practical understanding
- Implements unit tests for functionality and edge cases
This enhancement provides a streamlined way for developers to incorporate geolocation features into their applications.
Relates to enhancement request #93
> Adds useGeolocation hook with documentation and demo

- docs/README.md
- docs/demo/ClassesDemo.jsx
- docs/demo/styling/demo.css
- docs/docs/utilities/classes.mdx
- lib/index.ts
- lib/tests/utils/Classes.test.tsx
- lib/tests/utils/Classes.test.tsx.snap
- lib/utils/Classes.tsx
This PR relates to [issue 127](https://github.com/DavidHDev/haiku/issues/127).
This PR introduces a new utility component called `Classes` that simplifies conditional class name management in React components. The component provides a clean and type-safe way to conditionally apply multiple classes based on different conditions. It serves as an enhancement to the limitations of the `Class` utility component.
- Type-safe implementation with TypeScript.
- Support for multiple conditional classes using object mapping.
- Automatic class name deduplication.
- Flexible element type support through the `as` prop.
```jsx
<Classes
as="button"
className="base-class"
toggleClasses={{
'error': hasError,
'squared': isSquared,
'disabled': isDisabled
}}
>
Click me
</Classes>
```
- Added demo …
> Adds Classes utility component with documentation
